### ISSUE TITLE
[XHR Breakpoints] Make the method selector smaller

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8141]
With @Jaril's work in #8094 and https://github.com/firefox-devtools/ux/issues/45 we are going to have smaller XHR breakpoint items, 20px tall.

When going to edit mode, though, the input takes more vertical space:

1. The container's 1px border makes the height 22px instead of 20px. Maybe we should try an inset outline instead? As in: `outline: solid 1px; outline-offset: -1px;`.
2. The `<select>` itself is rather big, at least on Linux its easily more than 30px tall.

We have a minimal `<select>` style used in Firefox DevTools, for instance in the Responsive Design Mode toolbar or in the Network panel toolbar. We should reuse that style here.

I'm getting good results with this CSS:

```css
.xhr-input-method {
  margin-inline-start: 4px;
  padding-block: 0;
  padding-inline-start: 2px;
  padding-inline-end: 14px;
  border: none;
  border-radius: 2px;
  font: inherit;
  color: inherit;
  background-color: var(--toolbarbutton-background);
  -moz-appearance: none;
  appearance: none;
}
```

Then the only thing missing is adding the double-arrow icon to the right of the select.
