### ISSUE TITLE
Code is not monospace anymore in Launchpad (CSS selector issue)

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8164]
When using the launchpad (`yarn start` from `master`), `.devtools-monospace` and other code text is not monospace anymore:

![screenshot](https://user-images.githubusercontent.com/243601/55014197-d2421b00-4fea-11e9-8d20-65e8822b3fa8.png)

These styles rely on the `--monospace-font-family` which is defined in mozilla-central's `devtools/client/themes/common.css` like this:

```css
:root[platform="mac"] {
  --monospace-font-family: Menlo, monospace;
}

:root[platform="win"] {
  --monospace-font-family: Consolas, monospace;
}

:root[platform="linux"] {
  --monospace-font-family: monospace;
}
```

The launchpad document doesn't have the `platform` attribute on the `:root` element.

We may have changed something in the ways we include

Related issue: #7904.
